name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:  # to run this workflow manually from the Actions tab

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0  # Use a version that supports Node.js 20
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: git push https://huggingface.co/spaces/SURESHBEEKHANI/News-Research-Tool
